site_name: CContainerKit WIKI
site_url: https://catisnotfound.github.io/CContainerKit-Wiki
repo_url: https://github.com/CatIsNotFound/CContainerKit
repo_name: CatIsNotFound/CContainerKit
copyright: Copyright © 2025 CatIsNotFound

theme: 
  name: material
  features:
    - navigation.sections
    - search.suggest
    - search.highlight
    - search.share
  palette:
    primary: 'teal'
    accent: 'teal'
  icon:
    repo: fontawesome/brands/github
    
edit_uri: https://github.com/CatIsNotFound/CContainerKit-Wiki/tree/main/docs

markdown_extensions:
  - admonition
  - abbr
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 3
      baselevel: 1

nav:
  - Home: index.md
  - Quick Start: quickstart/index.md 
  - API Refenrence: 
    - Intro: apis/index.md
    - CArray: apis/CArray.md
    - CVector: apis/CVector.md
    - CString: apis/CString.md
    - CVariant: apis/CVariant.md
    - CDebug: apis/CDebug.md
  - Code Demos: demos/index.md
  - Get involved: contribute/index.md

plugins:
  - search

  - i18n:
      reconfigure_material: true
      reconfigure_search: true
      fallback_to_default: true
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: zh
          name: 简体中文
          build: true
          
      docs_structure: folder
  - git-revision-date-localized:
      type: timeago
      timezone: Asia/Shanghai
      fallback_to_build_date: true
      enable_creation_date: true
      exclude:
        - en/index.md
        - zh/index.md
      enable_git_follow: true
      enabled: true


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CatIsNotFound/
