site_name: CContainerKit WIKI
site_url: https://catisnotfound.github.io/CContainerKit-Wiki

theme: 
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 3
      baselevel: 1

nav:
  - Home: index.md
  - Quick Start: quickstart/index.md 
  - API Refenrence: 
    - Intro: apis/index.md
    - CArray: apis/CArray.md
    - CVector: apis/CVector.md
    - CString: apis/CString.md
    - CVariant: apis/CVariant.md
    - CDebug: apis/CDebug.md
  - Code Demos: demos/index.md
  - Get involved: contribute/index.md

plugins:
  - search
  - i18n:
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: zh
          name: 简体中文
          build: true
          
      docs_structure: folder

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CatIsNotFound/CContainerKit
